# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: gradle-matrix

on:
  workflow_call: # https://docs.github.com/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow

jobs:
  test:
    strategy:
      matrix:
        jdk:
          - '17.0.15'
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
        include:
          - os: ubuntu-latest
            gradlew_exec: ./gradlew
            gradlew_exec_permission: on
          - os: macos-latest
            gradlew_exec: ./gradlew
            gradlew_exec_permission: on
          - os: windows-latest
            gradlew_exec: .\gradlew
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'zulu'
          cache: gradle
      - if: ${{ matrix.gradlew_exec_permission }}
        name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - if: ${{ matrix.gradlew_exec }}
        name: Gradle buildEnvironment
        run: ${{ matrix.gradlew_exec }} buildEnvironment --warning-mode all
      - if: ${{ matrix.gradlew_exec }}
        name: Gradle guide clean test
        run: ${{ matrix.gradlew_exec }} designpatterns:clean designpatterns:test --info
      - if: ${{ matrix.gradlew_exec }}
        name: Gradle guide clean test
        run: ${{ matrix.gradlew_exec }} dashboard:clean dashboard:test --info