# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: gradle-codecov

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  jacoco:
    strategy:
      matrix:
        jdk:
          - '17.0.15'
        os:
          # - macos-latest
          # - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'zulu'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle dashboard clean test
        run: ./gradlew dashboard:clean dashboard:test --info
      - name: Build with Gradle dashboard jacocoTestReport
        run: ./gradlew dashboard:jacocoTestReport
      - name: Build with Gradle designpatterns clean test
        run: ./gradlew designpatterns:clean designpatterns:test --info
      - name: Build with Gradle designpatterns jacocoTestReport
        run: ./gradlew designpatterns:jacocoTestReport
      - name: Codecov
        uses: codecov/codecov-action@v1.2.1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          #        directory: ./dashboard/build/,./designpatterns/build/
          verbose: false