# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: gradle-matrix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        include:
          - os: ubuntu-latest
            gradlew_exec: ./gradlew
            gradlew_exec_permission: on
          - os: macos-latest
            gradlew_exec: ./gradlew
            gradlew_exec_permission: on
          - os: windows-latest
            gradlew_exec: .\gradlew
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - if: ${{ matrix.gradlew_exec_permission }}
        name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - if: ${{ matrix.gradlew_exec }}
        name: Gradle buildEnvironment
        run: ${{ matrix.gradlew_exec }} buildEnvironment --warning-mode all
      - if: ${{ matrix.gradlew_exec }}
        name: Gradle guide clean test
        run: ${{ matrix.gradlew_exec }} designpatterns:clean designpatterns:test --info
      - if: ${{ matrix.gradlew_exec }}
        name: Gradle guide clean test
        run: ${{ matrix.gradlew_exec }} dashboard:clean dashboard:test --info