# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java-CI-with-Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle buildEnvironment
      run: ./gradlew buildEnvironment --warning-mode all
    - name:  Build with Gradle dashboard clean test
      run: ./gradlew dashboard:clean dashboard:test --info
#    - name: Build with Gradle dashboard pitest
#      run: ./gradlew dashboard:pitest
    - name: Build with Gradle dashboard jacocoTestReport
      run: ./gradlew dashboard:jacocoTestReport
    - name: Build with Gradle designpatterns jacocoTestReport
      run: ./gradlew designpatterns:jacocoTestReport
    - name: Codecov
      uses: codecov/codecov-action@v1.2.1
      with:
        token: ${{secrets.CODECOV_TOKEN}}
#        directory: ./dashboard/build/,./designpatterns/build/
        verbose: false